version: "3.7"
services:
    database:
        container_name: scan_db
        image: mysql:8
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=change_me
            - MYSQL_DATABASE=scan      
        ports:
            - '3309:3306'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 30s
            retries: 3
    redis:
        container_name: redis_worker
        image: redis:7.0-alpine
        restart: always
        ports:
            - '6379:6379'        
    zookeeper:
        hostname: zookeeper
        image: wurstmeister/zookeeper:3.4.6
        expose:
            - "2181"
        ports:
            - "2181:2181"
    broker:
        image: wurstmeister/kafka
        env_file:
            - ./deployments/.kafka.env
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
            - '8082:8082'
            - '8083:8083'
    scan:
        build: .
        container_name: scan
        depends_on:
            - database
            - broker
        ports:
            - "8000:8080"
        env_file:
            - ./deployments/.dev.env        
        restart: always
    execution:
        build: .
        container_name: execution
        command: ["/repo/scripts/run.sh", "execution"]        
        depends_on:
            - broker
            - redis
        env_file:
            - ./deployments/.dev.env        
        restart: always
        