version: "3.7"
services:
    database:
        container_name: scan_db
        image: mysql:8
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=change_me
            - MYSQL_DATABASE=scan      
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 30s
            retries: 3
    zookeeper:
        hostname: zookeeper
        image: wurstmeister/zookeeper:3.4.6
        expose:
            - "2181"
        ports:
            - "2181:2181"
    broker:
        image: wurstmeister/kafka
        env_file:
            - ./deployments/.kafka.env
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
            - '8082:8082'
            - '8083:8083'
    api:
        build: .
        container_name: api
        depends_on:
            - database
            - broker
        ports:
            - "8000:8080"
        env_file:
            - ./deployments/.dev.env        
        restart: always
    worker:
        build: .
        container_name: worker
        command: ["/repo/scripts/run.sh", "worker"]        
        depends_on:
            - broker
        env_file:
            - ./deployments/.dev.env        
        restart: always